apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-project3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: kemiagbabiaka/kubernetes-clusters:latest
        ports:
        - containerPort: 8080
