apiVersion: v1
kind: Service
metadata:
  name: java-web-project-service
spec:
  selector:
    app: java-web-project3
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
