---
- name: Delete Kubernetes Cluster using Kops
  hosts: master
  become: yes

  vars:
    cluster_name: "k8s.local"
    state_store: "s3://k8sproject2-s3bucket"

  tasks:
    - name: Export KOPS environment variables
      lineinfile:
        path: ~/.bashrc
        line: 'export {{ item.key }}={{ item.value }}'
        create: yes
        insertafter: EOF
      loop:
        - { key: "KOPS_CLUSTER_NAME", value: "{{ cluster_name }}" }
        - { key: "KOPS_STATE_STORE", value: "{{ state_store }}" }

    - name: Delete Kops cluster
      shell: |
        export KOPS_CLUSTER_NAME={{ cluster_name }}
        export KOPS_STATE_STORE={{ state_store }}
        kops delete cluster --name=${KOPS_CLUSTER_NAME} --state=${KOPS_STATE_STORE} --yes
...