---
- name: Install tools for Kubernetes (Ubuntu)
  hosts: master
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required base tools
      apt:
        name:
          - unzip
          - curl
          - python3
          - python3-pip
          - git
          - software-properties-common
        state: present

    - name: Ensure pip3 is available
      command: which pip3
      register: pip3_check
      failed_when: pip3_check.rc != 0

    - name: Install AWS CLI using pip3
      pip:
        name: awscli
        executable: pip3

    - name: Download latest stable version of kubectl
      become: yes
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      args:
        chdir: /tmp
        creates: /tmp/kubectl

    - name: Install kubectl binary
      become: yes
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Kops
      get_url:
        url: https://github.com/kubernetes/kops/releases/download/v1.28.0/kops-linux-amd64
        dest: /usr/local/bin/kops
        mode: '0755'
...