---
- name: Install tools for Kubernetes
  hosts: master
  become: yes

  tasks:
    - name: Install unzip, curl, and pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - curl
        - python3
        - git

    - name: Install AWS CLI
      pip:
        name: awscli

    - name: Install kubectl
      get_url:
        url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.2/2023-10-26/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Kops
      get_url:
        url: https://github.com/kubernetes/kops/releases/download/v1.28.0/kops-linux-amd64
        dest: /usr/local/bin/kops
        mode: '0755'
