[master]
3.145.107.134 ansible_user=ubuntu

[workers]
3.131.98.156 ansible_user=ubuntu
3.133.121.120 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/ubuntu/.ssh/zeecentoskey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
